version: 2
jobs:
  install:
    docker:
      - image: node:11.1.0
    steps:
      - checkout
      - run:
          name: Yarn install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  check:
    docker:
      - image: node:11.1.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Test
          command: npm test
      - run:
          name: Run Lint
          command: npm run lint:check
      - run:
          name: Run Prettier
          command: npm run prettier:check

  build:
    docker:
      - image: node:11.1.0
    steps:
      - checkout
      - run:
          name: Deploy Dev to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git Dev

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - install
      - check:
          requires:
            - install
      - build:
          requires:
            - check
          filters:
            branches:
              only:
                - dev
